version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - 27017:27017
    networks:
      - my-net
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment: 
      ME_CONFIG_MONGODB_SERVER: mongodb 
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: root123
    ports:
      - 8081:8081
    networks:
      - my-net
    depends_on:
      - "mongodb"
    
networks:
  my-net:
    name: my-app
